ClickMart/ClickMart/urls.py
# fix image not showing in index
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from core.views import index, contact

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # fix images not showing in index

ClickMart/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm

app_name = 'core'

# separa as rotas
urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html',authentication_form=LoginForm), name='login'),
    path('logout/', views.logout, name='logout'),
]

ClickMart/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
]

ClickMart/core/models.py
from django.db import models

# Create your models here.

ClickMart/item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'categories'


    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

ClickMart/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User




class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Seu nome de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Seu Email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirme sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Seu nome de usuario',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Sua senha',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

ClickMart/item/forms.py
from django import forms

from .models import Item

inputClasses = 'w-full py-4 px-6 rounded-xl border'

class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'price', 'image')

        widgets = {
            'category': forms.Select(attrs={
                'class': inputClasses
            }),
            'name': forms.TextInput(attrs={
                'class': inputClasses,
            }),
            'description': forms.Textarea(attrs={
                'class': inputClasses,
            }),
            'price': forms.TextInput(attrs={
                'class': inputClasses,
            }),
            'image': forms.FileInput(attrs={
                'class': inputClasses,
            })
        }

ClickMart/core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout as logouts

# importa os modelos
from item.models import Category, Item

from .forms import SignUpForm


def index(request):
    items = Item.objects.filter(is_sold=False).order_by('-created_at')
    categories = Category.objects.all()

    # passa os itens e categorias para o template
    return render(request, 'core/index.html', {
        'items': items,
        'categories': categories
    })

def contact(request):
    return render(request, 'core/contact.html')

def logout(request):
    if request.method == "POST":
        logouts(request)
        return redirect('/')


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignUpForm()

    return render(request, 'core/signup.html', {
        'form': form
    })



ClickMart/item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Item
from .forms import NewItemForm

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_sold=False).exclude(pk=pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False) # se salvar direto o created by fica vazio, disparando um erro
            item.created_by = request.user
            item.save() # agora podemos salvar o item

            return redirect('item:detail', pk=item.pk)
            


    form = NewItemForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Novo produto',
    })
    


ClickMart/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://cdn.tailwindcss.com"></script>
    <title> {% block title %}{% endblock %} | ClickMart</title>
</head>
<body>

    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="/" class="text-xl font-semibold">ClickMart
            {% if request.user.is_authenticated %}
            <p class="text-gray-500 text-xl">Bem vindo, {{ request.user.username }}!</p>
            {% endif %}
        </a>

        


        <div class="space-x-6">
            <a href="#" class="text-lg font-semibold hover:text-gray-500">Buscar</a>
            <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">Adicionar Produto</a>

            {% if request.user.is_authenticated %}

            <a 
                href="#" 
                class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-sky-950"
            >
                Mensagens
            </a>
            <a 
                href="#" 
                class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-sky-950"
            >
                Perfil
            </a>



            {% else %}

                <a 
                    href="{% url 'core:signup' %}" 
                    class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-sky-950"
                >
                    Registrar
                </a>
                <a 
                    href="{% url 'core:login' %}" 
                    class="px-6 py-3 text-lg font-semibold bg-sky-900 text-white rounded-xl hover:bg-sky-950"
                >
                    Logar
                </a>

            {% endif %}

            {% if request.user.is_authenticated %}
                <form action="{% url 'core:logout' %}" method="POST" class="inline-block">
                    {% csrf_token %}
                    <button
                        value="Logout"
                        type="submit"
                        class="px-6 py-2 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700"
                    >
                        Sair
                    </button>
                </form>
            {% endif %}



            
        </div>
    </nav>

    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">Sobre</h3>
            <p class="text-lg text-gray-500">Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam dolor perferendis vero quibusdam placeat provident possimus magni magnam dignissimos, impedit eaque ipsam nobis rerum quo. Earum laudantium perspiciatis possimus ut.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li>
                    <a href="#" class="text-lg text-sky-600 hover:text-sky-700">Sobre</a>
                </li>
                <li>
                    <a href="{% url 'core:contact' %}" class="text-lg text-sky-600 hover:text-sky-700">Contato<a>
                </li>
                <li>
                    <a href="#" class="text-lg text-sky-600 hover:text-sky-700">Privacidade<a>
                </li>
                <li>
                    <a href="#" class="text-lg text-sky-600 hover:text-sky-700">Termos de uso<a>
                </li>
            </ul>
        </div>
    </footer>
    
</body>
</html>

ClickMart/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}

<h1>The contact page</h1>

{% endblock %}

ClickMart/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl overflow-hidden">
        <h2 class="mb-12 text-2xl text-center">Produtos Recentes</h2>

        <div class="grid md:grid-cols-3 xl:grid-cols-4 gap-3">
            {% for item in items %}
                <div class="rounded-xl w-58">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="object-fill h-96 w-full rounded-t-xl" />
                        </div>
                        <div class="p-6 bg-white rounded-b-xl h-40">
                            <h2 class="text-2xl h-16 text-ellipsis overflow-hidden">{{ item.name }}</h2>
                            <p class="text-gray-500">R$ {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categorias</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} produtos</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>

{% endblock %}

ClickMart/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

    
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-5 text-3xl">Logar</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2">Nome de Usuario</label>
                <br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Senha</label>
                <br>
                {{ form.password }}
            </div>

            {% if forms.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="py-4 px-8 bg-gray-900 hover:bg-sky-800 rounded-xl text-white">
                Logar
            </button>
        </form>

    </div>

{% endblock %}

ClickMart/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

    
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="mb-5 text-3xl">Registrar</h1>

        <form method="post" action=".">
            {% csrf_token %}

            

            <div class="mb-3">
                <label class="inline-block mb-2">Nome de Usuario</label>
                <br>
                {{ form.username }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Email</label>
                <br>
                {{ form.email }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Senha</label>
                <br>
                {{ form.password1 }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2">Confirme sua senha</label>
                <br>
                {{ form.password2 }}
            </div>

            {% if forms.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            {% endif %}

            <button type="submit" class="py-4 px-8 bg-gray-900 hover:bg-sky-800 rounded-xl text-white">
                Registrar
            </button>
        </form>

    </div>

{% endblock %}

ClickMart/item/templates/item/detail.html
{% extends 'core/base.html' %}


{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="grid grid-cols-5 gap-6">
        
        <div class="col-span-3">
            <img src="{{ item.image.url }}" class="rounded-xl" alt="{{ item.name }}">
        </div>

        <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
            <p class="text-gray-400 text-xl mb-3">{{ item.category }} </p>
            <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
            <p class="text-sky-900 font-semibold text-2xl">R$ {{ item.price }}</p>
            <p class="text-gray-500">Vendedor: {{ item.created_by.username }}</p>

            <a href="#" class="inline-block mb-6 mt-6 px-6 py-3 text-lg bg-sky-900 text-white rounded-xl hover:bg-sky-700">Contatar Vendedor</a>

            {% if item.description %}

                <p><strong class="text-grey-500">Descrição:</strong></p>
                <div class="h-52 overflow-scroll">
                    <p class="text-gray-700">
                        
                        {{ item.description }}
                    </p>
                </div>

            {% else %}

                <p class="text-gray-500">Não há descrição para este item</p>

            {% endif %}
            
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Produtos Semelhantes</h2>

        <div class="grid grid-cols-3 gap-4 xl:grid-cols-5">
            {% for item in related_items %}
                <div class="rounded-xl">
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="object-fill h-65 w-full rounded-t-xl" />
                        </div>
                        <div class="p-6 bg-white rounded-b-xl h-40">
                            <h2 class="text-2xl h-16 text-ellipsis overflow-hidden">{{ item.name }}</h2>
                            <p class="text-gray-500">R$ {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

ClickMart/item/templates/item/form.html
{% extends 'core/base.html' %}
{% block title %}{{title}}{% endblock %}


{% block content %}
    <h1 class="mb-6 text-3xl">{{ title }}</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}

        <div class="space-y-4">
            {{ form.as_p }}
        </div>

        {% if forms.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl">
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
        {% endif %}

        <button type="submit" class="mt-3 py-4 px-8 bg-gray-900 hover:bg-sky-800 rounded-xl text-white">
            Publicar Produto
        </button>


    </form>

{% endblock %}